DataDir = "/root/.coschain"
LogLevel = "debug"
Name = "cosd"

[Consensus]
  BootStrap = false
  LocalBpName = ""
  LocalBpPrivateKey = ""
  Type = "SABFT"

[GRPC]
  HTTPCors = ["*"]
  HTTPLimit = 100
  HTTPListen = "0.0.0.0:8080"
  RPCListen = "0.0.0.0:8888"
  RPCName = "rpc"

[P2P]
  CAPath = ""
  CertPath = ""
  DualPortSupport = true
  EnableConsensus = true
  IsTLS = false
  KeyPath = ""
  MaxConnInBound = 1024
  MaxConnInBoundForSingleIP = 16
  MaxConnOutBound = 1024
  NetworkId = 1
  NetworkMagic = 2356652902
  NetworkName = "contentos"
  NodeConsensusPort = 20339
  NodePort = 20338
  ReservedPeersOnly = false

  [P2P.Genesis]
    SeedList = ["34.230.216.41:20338", "107.23.54.2:20338", "52.20.31.199:20338", "100.24.80.16:20338"]

  [P2P.ReservedCfg]
    MaskPeers = []
    ReservedPeers = []
